services:
  tg-bot:
    restart: on-failure
    environment:
      CONFIG_PATH: /etc/south_coffee_config/config.json
    volumes:
      - ${CONFIG_DIR}:/etc/south_coffee_config
  postgres:
    restart: on-failure
  postgres-backups:
    image: prodrigestivill/postgres-backup-local
    profiles: ['all', 'backups']
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      POSTGRES_EXTRA_OPTS: -Z6 --schema=${POSTGRES_BACKUP_SCHEMA} --blobs
      SCHEDULE: ${POSTGRES_BACKUP_SCHEDULE}
      BACKUP_KEEP_DAYS: ${POSTGRES_BACKUP_KEEP_DAYS}
      BACKUP_KEEP_WEEKS: ${POSTGRES_BACKUP_KEEP_WEEKS}
      BACKUP_KEEP_MONTHS: ${POSTGRES_BACKUP_KEEP_MONTHS}
      HEALTHCHECK_PORT: 8080
    volumes:
      - ${POSTGRES_BACKUP_DIR}:/backups